<Project>

  <PropertyGroup>
    <TUnitVersion>1.67.0</TUnitVersion>
    <NukeCommonVersion>10.1.0</NukeCommonVersion>
    <ANcpLuaAnalyzersVersion>2.1.2</ANcpLuaAnalyzersVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="TUnit" Version="$(TUnitVersion)" />
    <PackageVersion Include="Nuke.Common" Version="$(NukeCommonVersion)" />
    <PackageVersion Include="Nuke.Components" Version="$(NukeCommonVersion)" />
    <PackageVersion Include="ANcpLua.Analyzers" Version="$(ANcpLuaAnalyzersVersion)" />
  </ItemGroup>

</Project>
